// react/components/mood-calendar.tsx
"use client";

import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import type { MoodEntry } from "@/types/mood";
import { ChevronLeft, ChevronRight, Calendar } from "lucide-react";

interface MoodCalendarProps {
  entries: MoodEntry[];
}

export default function MoodCalendar({ entries }: MoodCalendarProps) {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedDay, setSelectedDay] = useState<MoodEntry | null>(null);

  const getDaysInMonth = (year: number, month: number) => {
    return new Date(year, month + 1, 0).getDate();
  };

  const getFirstDayOfMonth = (year: number, month: number) => {
    return new Date(year, month, 1).getDay();
  };

  const year = currentDate.getFullYear();
  const month = currentDate.getMonth();
  const daysInMonth = getDaysInMonth(year, month);
  const firstDayOfMonth = getFirstDayOfMonth(year, month);

  const prevMonth = () => {
    setCurrentDate(new Date(year, month - 1, 1));
    setSelectedDay(null);
  };

  const nextMonth = () => {
    setCurrentDate(new Date(year, month + 1, 1));
    setSelectedDay(null);
  };

  const getMoodForDay = (day: number): MoodEntry | undefined => {
    const dateStr = `${year}-${String(month + 1).padStart(2, "0")}-${String(
      day,
    ).padStart(2, "0")}`;
    return entries.find((entry) => entry.date.startsWith(dateStr));
  };

  const handleDayClick = (day: number) => {
    const entry = getMoodForDay(day);
    setSelectedDay(entry || null);
  };

  const getMoodColor = (mood: string) => {
    switch (mood) {
      case "😊":
        return "bg-gradient-to-br from-green-400 to-emerald-500 text-white";
      case "😐":
        return "bg-gradient-to-br from-amber-400 to-yellow-500 text-white";
      case "😞":
        return "bg-gradient-to-br from-red-400 to-rose-500 text-white";
      default:
        return "";
    }
  };

  const days = [];
  for (let i = 0; i < firstDayOfMonth; i++) {
    days.push(<div key={`empty-${i}`} className="h-10 w-10"></div>);
  }

  for (let day = 1; day <= daysInMonth; day++) {
    const entry = getMoodForDay(day);
    const isToday =
      new Date().getDate() === day &&
      new Date().getMonth() === month &&
      new Date().getFullYear() === year;

    days.push(
      <button
        key={day}
        onClick={() => handleDayClick(day)}
        className={`h-10 w-10 rounded-full flex items-center justify-center transition-all duration-200 
          ${
            isToday
              ? "ring-2 ring-primary ring-offset-2 dark:ring-offset-gray-900"
              : ""
          }
          ${entry ? getMoodColor(entry.mood) : "hover:bg-secondary"}`}
      >
        <div className="relative">
          <span>{day}</span>
        </div>
      </button>,
    );
  }

  return (
    <div>
      <Card className="mb-6 border-none overflow-hidden bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm">
        <CardContent className="p-6">
          <div className="flex justify-between items-center mb-6">
            <Button
              variant="outline"
              size="icon"
              onClick={prevMonth}
              className="rounded-full border-primary/20 hover:bg-primary/10"
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <div className="flex items-center gap-2">
              <Calendar className="h-5 w-5 text-primary" />
              <h3 className="text-lg font-medium">
                {currentDate.toLocaleDateString("en-US", {
                  month: "long",
                  year: "numeric",
                })}
              </h3>
            </div>
            <Button
              variant="outline"
              size="icon"
              onClick={nextMonth}
              className="rounded-full border-primary/20 hover:bg-primary/10"
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>

          <div className="grid grid-cols-7 gap-1 text-center mb-3">
            {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => (
              <div
                key={day}
                className="text-sm font-medium text-muted-foreground"
              >
                {day}
              </div>
            ))}
          </div>

          <div className="grid grid-cols-7 gap-1 justify-items-center">
            {days}
          </div>
        </CardContent>
      </Card>

      {selectedDay && (
        <Card className="animate-fadeIn border-none overflow-hidden bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm">
          <CardContent className="p-6">
            <div className="flex items-center gap-4 mb-4">
              <div
                className={`flex items-center justify-center w-12 h-12 rounded-full shadow-sm ${getMoodColor(
                  selectedDay.mood,
                )}`}
              >
                <span className="text-3xl">{selectedDay.mood}</span>
              </div>
              <h3 className="text-lg font-medium">
                {new Date(selectedDay.date).toLocaleDateString("en-US", {
                  weekday: "long",
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
              </h3>
            </div>
            {selectedDay.note ? (
              <div className="p-4 rounded-lg bg-secondary/30 backdrop-blur-sm">
                <p className="whitespace-pre-wrap">{selectedDay.note}</p>
              </div>
            ) : (
              <p className="text-muted-foreground italic">
                No notes for this day
              </p>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}

// vue/src/components/MoodCalendar.vue
<template>
  <div class="p-6 rounded-xl shadow-lg">
    <div class="flex justify-between items-center mb-6">
      <button
        @click="prevMonth"
        class="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M15 19l-7-7 7-7"
          />
        </svg>
      </button>

      <h2 class="text-2xl font-bold">{{ monthName }} {{ year }}</h2>

      <button
        @click="nextMonth"
        class="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M9 5l7 7-7 7"
          />
        </svg>
      </button>
    </div>

    <div class="grid grid-cols-7 gap-1 text-center mb-2">
      <div v-for="day in weekdays" :key="day" class="font-medium text-sm py-1">
        {{ day }}
      </div>
    </div>

    <div class="grid grid-cols-7 gap-1">
      <!-- Empty cells for days before the first day of the month -->
      <div
        v-for="_ in firstDayOfMonth"
        :key="'empty-' + _"
        class="aspect-square"
      ></div>

      <!-- Calendar days -->
      <div v-for="day in daysInMonth" :key="day" class="aspect-square p-1">
        <div
          class="h-full w-full flex flex-col items-center justify-center rounded-full relative"
          :class="getDayClass(day)"
        >
          <span class="text-sm">{{ day }}</span>
          <span v-if="getMoodForDay(day)" class="absolute bottom-1 text-xs">
            {{ getMoodForDay(day) }}
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from "vue";
import {
  getDaysInMonth,
  getFirstDayOfMonth,
  getDateForDay,
} from "../utils/date-utils";
import { getEntryForDate } from "../utils/mood-utils";

const props = defineProps({
  entries: {
    type: Array,
    required: true,
  },
});

const currentDate = new Date();
const currentMonth = ref(currentDate.getMonth());
const currentYear = ref(currentDate.getFullYear());

const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

const monthName = computed(() => {
  return new Date(currentYear.value, currentMonth.value).toLocaleString(
    "default",
    { month: "long" },
  );
});

const daysInMonth = computed(() => {
  return getDaysInMonth(currentYear.value, currentMonth.value);
});

const firstDayOfMonth = computed(() => {
  return getFirstDayOfMonth(currentYear.value, currentMonth.value);
});

const year = computed(() => {
  return currentYear.value;
});

function prevMonth() {
  if (currentMonth.value === 0) {
    currentMonth.value = 11;
    currentYear.value--;
  } else {
    currentMonth.value--;
  }
}

function nextMonth() {
  if (currentMonth.value === 11) {
    currentMonth.value = 0;
    currentYear.value++;
  } else {
    currentMonth.value++;
  }
}

function getMoodForDay(day) {
  const date = getDateForDay(currentYear.value, currentMonth.value, day);
  const entry = getEntryForDate(props.entries, date);
  return entry ? entry.mood : null;
}

function getDayClass(day) {
  const date = getDateForDay(currentYear.value, currentMonth.value, day);
  const today = new Date();
  const isToday =
    date.getDate() === today.getDate() &&
    date.getMonth() === today.getMonth() &&
    date.getFullYear() === today.getFullYear();

  const mood = getMoodForDay(day);

  let moodClass = "";
  if (mood) {
    switch (mood) {
      case "😊":
        moodClass = "bg-green-100 dark:bg-green-900/30";
        break;
      case "😐":
        moodClass = "bg-yellow-100 dark:bg-yellow-900/30";
        break;
      case "😞":
        moodClass = "bg-red-100 dark:bg-red-900/30";
        break;
    }
  }

  return {
    "border border-blue-500": isToday,
    [moodClass]: mood,
    "hover:bg-gray-100 dark:hover:bg-gray-700": !mood,
  };
}
</script>
