// react/app/page.tsx
"use client";

import { useState, useEffect } from "react";
import MoodForm from "@/components/mood-form";
import MoodHistory from "@/components/mood-history";
import MoodCalendar from "@/components/mood-calendar";
import ThemeToggle from "@/components/theme-toggle";
import type { MoodEntry } from "@/types/mood";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Sparkles } from "lucide-react";

export default function Home() {
  const [moodEntries, setMoodEntries] = useState<MoodEntry[]>([]);

  // Load mood entries from localStorage on initial render
  useEffect(() => {
    const savedEntries = localStorage.getItem("moodEntries");
    if (savedEntries) {
      setMoodEntries(JSON.parse(savedEntries));
    }
  }, []);

  // Save mood entries to localStorage whenever they change
  useEffect(() => {
    localStorage.setItem("moodEntries", JSON.stringify(moodEntries));
  }, [moodEntries]);

  const addMoodEntry = (entry: MoodEntry) => {
    // Check if there's already an entry for today
    const today = new Date().toISOString().split("T")[0];
    const existingEntryIndex = moodEntries.findIndex(
      (e) => e.date.split("T")[0] === today,
    );

    if (existingEntryIndex !== -1) {
      // Update existing entry
      const updatedEntries = [...moodEntries];
      updatedEntries[existingEntryIndex] = entry;
      setMoodEntries(updatedEntries);
    } else {
      // Add new entry
      setMoodEntries([...moodEntries, entry]);
    }
  };

  return (
    <main className="min-h-screen p-4 md:p-8 transition-colors duration-300 bg-background">
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-between items-center mb-8">
          <div className="flex items-center gap-2">
            <Sparkles className="h-6 w-6 text-primary animate-pulse-slow" />
            <h1 className="text-3xl font-bold bg-gradient-to-r from-primary to-purple-400 dark:to-purple-300 bg-clip-text text-transparent">
              Mood Journal
            </h1>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-sm text-muted-foreground hidden md:inline-block">
              Theme
            </span>
            <ThemeToggle />
          </div>
        </div>

        <MoodForm onAddEntry={addMoodEntry} entries={moodEntries} />

        <Tabs defaultValue="timeline" className="mt-10">
          <TabsList className="grid w-full grid-cols-2 mb-6 rounded-full p-1 bg-secondary/50 backdrop-blur-sm">
            <TabsTrigger
              value="timeline"
              className="rounded-full data-[state=active]:bg-white dark:data-[state=active]:bg-gray-800 data-[state=active]:text-primary data-[state=active]:shadow-sm"
            >
              Timeline
            </TabsTrigger>
            <TabsTrigger
              value="calendar"
              className="rounded-full data-[state=active]:bg-white dark:data-[state=active]:bg-gray-800 data-[state=active]:text-primary data-[state=active]:shadow-sm"
            >
              Calendar
            </TabsTrigger>
          </TabsList>
          <TabsContent value="timeline" className="mt-4 animate-fadeIn">
            <MoodHistory entries={moodEntries} />
          </TabsContent>
          <TabsContent value="calendar" className="mt-4 animate-fadeIn">
            <MoodCalendar entries={moodEntries} />
          </TabsContent>
        </Tabs>
      </div>
    </main>
  );
}

// vue/src/App.vue
<template>
  <div
    class="min-h-screen transition-colors duration-300"
    :class="isDarkMode ? 'dark bg-gray-900' : 'bg-gray-50'"
  >
    <div class="container mx-auto px-4 py-8 max-w-4xl">
      <header class="flex justify-between items-center mb-8">
        <h1
          class="text-3xl font-bold bg-gradient-to-r from-blue-500 to-purple-600 bg-clip-text text-transparent"
        >
          Mood Journal
        </h1>
        <ThemeToggle :isDarkMode="isDarkMode" @toggle-theme="toggleTheme" />
      </header>

      <main class="grid gap-8 md:grid-cols-[1fr_1.5fr]">
        <div class="order-2 md:order-1">
          <MoodForm
            @save-entry="addMoodEntry"
            :class="isDarkMode ? 'bg-gray-800 text-white' : 'bg-white'"
          />
        </div>
        <div class="order-1 md:order-2 space-y-8">
          <div class="tabs flex space-x-2 mb-4">
            <button
              @click="activeTab = 'history'"
              class="px-4 py-2 rounded-lg transition-colors"
              :class="
                activeTab === 'history'
                  ? isDarkMode
                    ? 'bg-gray-700 text-white'
                    : 'bg-blue-500 text-white'
                  : isDarkMode
                    ? 'text-gray-400 hover:bg-gray-700'
                    : 'text-gray-600 hover:bg-gray-200'
              "
            >
              Timeline
            </button>
            <button
              @click="activeTab = 'calendar'"
              class="px-4 py-2 rounded-lg transition-colors"
              :class="
                activeTab === 'calendar'
                  ? isDarkMode
                    ? 'bg-gray-700 text-white'
                    : 'bg-blue-500 text-white'
                  : isDarkMode
                    ? 'text-gray-400 hover:bg-gray-700'
                    : 'text-gray-600 hover:bg-gray-200'
              "
            >
              Calendar
            </button>
          </div>

          <MoodHistory
            v-if="activeTab === 'history'"
            :entries="sortedEntries"
            :class="isDarkMode ? 'bg-gray-800 text-white' : 'bg-white'"
          />
          <MoodCalendar
            v-else
            :entries="moodEntries"
            :class="isDarkMode ? 'bg-gray-800 text-white' : 'bg-white'"
          />
        </div>
      </main>
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted, ref, watch } from "vue";
import MoodCalendar from "./components/MoodCalendar.vue";
import MoodForm from "./components/MoodForm.vue";
import MoodHistory from "./components/MoodHistory.vue";
import ThemeToggle from "./components/ThemeToggle.vue";
import { sortEntriesByDate } from "./utils/mood-utils";
import {
  loadEntriesFromStorage,
  saveEntriesToStorage,
} from "./utils/storage-utils";

// State
const moodEntries = ref([]);
const activeTab = ref("history");
const isDarkMode = ref(false);

// Computed
const sortedEntries = computed(() => {
  return sortEntriesByDate(moodEntries.value);
});

// Methods
function addMoodEntry(entry) {
  // Check if there's an entry for the same day
  const today = new Date(entry.date).toISOString().split("T")[0];
  const existingEntryIndex = moodEntries.value.findIndex(
    (e) => new Date(e.date).toISOString().split("T")[0] === today,
  );

  if (existingEntryIndex !== -1) {
    // Update existing entry
    moodEntries.value[existingEntryIndex] = entry;
  } else {
    // Add new entry
    moodEntries.value.push(entry);
  }
}

function toggleTheme() {
  isDarkMode.value = !isDarkMode.value;
  localStorage.setItem("darkMode", isDarkMode.value ? "dark" : "light");
}

// Lifecycle
onMounted(() => {
  // Load entries from localStorage
  const savedEntries = loadEntriesFromStorage();
  if (savedEntries.length > 0) {
    moodEntries.value = savedEntries;
  }

  // Load theme preference
  const savedTheme = localStorage.getItem("darkMode");
  if (savedTheme) {
    isDarkMode.value = savedTheme === "dark";
  } else {
    // Check system preference
    const prefersDark = window.matchMedia(
      "(prefers-color-scheme: dark)",
    ).matches;
    isDarkMode.value = prefersDark;
  }
});

// Watch for changes to save to localStorage
watch(
  moodEntries,
  (newEntries) => {
    saveEntriesToStorage(newEntries);
  },
  { deep: true },
);
</script>

<style>
@import "./assets/main.css";

.dark {
  @apply text-white;
}
</style>
