// vue/src/components/MoodHistory.vue
<template>
  <div class="p-6 rounded-xl shadow-lg">
    <h2 class="text-2xl font-bold mb-6">Your Mood Timeline</h2>

    <div
      v-if="entries.length === 0"
      class="text-center py-8 text-gray-500 dark:text-gray-400"
    >
      <p>No mood entries yet. Add your first mood!</p>
    </div>

    <ul v-else class="space-y-4">
      <li
        v-for="entry in entries"
        :key="entry.id"
        class="p-4 rounded-lg border transition-colors"
        :class="getBorderColorClass(entry.mood)"
      >
        <div class="flex justify-between items-start">
          <div class="flex items-center">
            <span class="text-3xl mr-3">{{ entry.mood }}</span>
            <div>
              <p class="font-medium">{{ formatDate(entry.date) }}</p>
              <p class="text-gray-600 dark:text-gray-300 mt-1">
                {{ entry.note || "No note added" }}
              </p>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { defineProps } from "vue";

defineProps({
  entries: {
    type: Array,
    required: true,
  },
});

function formatDate(dateString) {
  const date = new Date(dateString);
  return new Intl.DateTimeFormat("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(date);
}

function getBorderColorClass(mood) {
  switch (mood) {
    case "😊":
      return "border-green-300 dark:border-green-700 bg-green-50 dark:bg-green-900/20";
    case "😐":
      return "border-yellow-300 dark:border-yellow-700 bg-yellow-50 dark:bg-yellow-900/20";
    case "😞":
      return "border-red-300 dark:border-red-700 bg-red-50 dark:bg-red-900/20";
    default:
      return "border-gray-300 dark:border-gray-700";
  }
}
</script>

// react/components/mood-history.tsx
"use client";

import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import type { MoodEntry } from "@/types/mood";
import { formatDistanceToNow } from "date-fns";
import { ChevronDown, ChevronUp } from "lucide-react";

interface MoodHistoryProps {
  entries: MoodEntry[];
}

export default function MoodHistory({ entries }: MoodHistoryProps) {
  const [expandedEntryId, setExpandedEntryId] = useState<string | null>(null);

  // Sort entries by date (newest first)
  const sortedEntries = [...entries].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime(),
  );

  const toggleExpand = (id: string) => {
    setExpandedEntryId(expandedEntryId === id ? null : id);
  };

  const getMoodColor = (mood: string) => {
    switch (mood) {
      case "😊":
        return "bg-gradient-to-br from-green-400/20 to-emerald-500/20 border-green-400/30";
      case "😐":
        return "bg-gradient-to-br from-amber-400/20 to-yellow-500/20 border-amber-400/30";
      case "😞":
        return "bg-gradient-to-br from-red-400/20 to-rose-500/20 border-red-400/30";
      default:
        return "";
    }
  };

  if (entries.length === 0) {
    return (
      <div className="text-center p-10 rounded-xl bg-secondary/30 backdrop-blur-sm border border-primary/10">
        <p className="text-lg">
          No mood entries yet. Start tracking your mood today!
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {sortedEntries.map((entry) => (
        <Card
          key={entry.id}
          className={`overflow-hidden transition-all duration-300 hover:shadow-md border-none ${getMoodColor(
            entry.mood,
          )}`}
          onClick={() => toggleExpand(entry.id)}
        >
          <CardContent className="p-5">
            <div className="flex justify-between items-center">
              <div className="flex items-center gap-4">
                <div className="flex items-center justify-center w-12 h-12 rounded-full bg-white dark:bg-gray-800 shadow-sm">
                  <span className="text-3xl">{entry.mood}</span>
                </div>
                <div>
                  <p className="font-medium">
                    {new Date(entry.date).toLocaleDateString("en-US", {
                      weekday: "long",
                      year: "numeric",
                      month: "long",
                      day: "numeric",
                    })}
                  </p>
                  <p className="text-sm text-muted-foreground">
                    {formatDistanceToNow(new Date(entry.date), {
                      addSuffix: true,
                    })}
                  </p>
                </div>
              </div>
              <button
                className="text-muted-foreground hover:text-foreground transition-colors p-2 rounded-full hover:bg-secondary/50"
                aria-label={
                  expandedEntryId === entry.id
                    ? "Collapse entry"
                    : "Expand entry"
                }
              >
                {expandedEntryId === entry.id ? (
                  <ChevronUp size={18} />
                ) : (
                  <ChevronDown size={18} />
                )}
              </button>
            </div>

            {expandedEntryId === entry.id && entry.note && (
              <div className="mt-4 pt-4 border-t border-primary/10 animate-fadeIn">
                <p className="whitespace-pre-wrap">{entry.note}</p>
              </div>
            )}
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
