// vue/src/components/MoodForm.vue
<template>
  <div class="p-6 rounded-xl shadow-lg transition-all">
    <h2 class="text-2xl font-bold mb-6 text-center">
      How are you feeling today?
    </h2>

    <div class="mood-selector flex justify-center gap-4 mb-6">
      <button
        v-for="mood in moods"
        :key="mood"
        @click="selectedMood = mood"
        class="text-4xl p-3 rounded-full transition-transform transform hover:scale-110"
        :class="
          selectedMood === mood
            ? 'bg-blue-100 dark:bg-blue-900 ring-2 ring-blue-500 scale-110'
            : ''
        "
      >
        {{ mood }}
      </button>
    </div>

    <div class="mb-6">
      <label for="note" class="block mb-2 font-medium"
        >Add a note (optional)</label
      >
      <textarea
        id="note"
        v-model="note"
        rows="3"
        class="w-full p-3 border rounded-lg resize-none focus:ring-2 focus:ring-blue-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600"
        placeholder="Write about your day..."
      ></textarea>
    </div>

    <button
      @click="saveEntry"
      :disabled="!selectedMood"
      class="w-full py-3 px-4 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-lg font-medium transition-opacity hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed"
    >
      Save Entry
    </button>
  </div>
</template>

<script setup>
import { ref } from "vue";
import { createMoodEntry } from "../utils/mood-utils";

const moods = ["😊", "😐", "😞"];
const selectedMood = ref("");
const note = ref("");

const emit = defineEmits(["save-entry"]);

function saveEntry() {
  if (!selectedMood.value) return;

  const entry = createMoodEntry(selectedMood.value, note.value);
  emit("save-entry", entry);

  // Reset form
  selectedMood.value = "";
  note.value = "";
}
</script>

// react/components/mood-form.tsx
"use client";

import { useState, useEffect } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import type { MoodEntry, MoodType } from "@/types/mood";
import { useTheme } from "next-themes";
import { HeartHandshake } from "lucide-react";

interface MoodFormProps {
  onAddEntry: (entry: MoodEntry) => void;
  entries: MoodEntry[];
}

export default function MoodForm({ onAddEntry, entries }: MoodFormProps) {
  const [selectedMood, setSelectedMood] = useState<MoodType | null>(null);
  const [note, setNote] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [todayEntry, setTodayEntry] = useState<MoodEntry | null>(null);
  const { resolvedTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  // Only render theme-dependent UI on the client to avoid hydration mismatch
  useEffect(() => {
    setMounted(true);
  }, []);

  // Check if there's already an entry for today
  useEffect(() => {
    const today = new Date().toISOString().split("T")[0];
    const existingEntry = entries.find((e) => e.date.split("T")[0] === today);

    if (existingEntry) {
      setTodayEntry(existingEntry);
      setSelectedMood(existingEntry.mood);
      setNote(existingEntry.note);
    } else {
      setTodayEntry(null);
      setSelectedMood(null);
      setNote("");
    }
  }, [entries]);

  const moods: MoodType[] = ["😊", "😐", "😞"];
  const moodColors = {
    "😊": "bg-gradient-to-br from-green-400 to-emerald-500",
    "😐": "bg-gradient-to-br from-amber-400 to-yellow-500",
    "😞": "bg-gradient-to-br from-red-400 to-rose-500",
  };

  const handleSubmit = () => {
    if (!selectedMood) return;

    setIsSubmitting(true);

    const newEntry: MoodEntry = {
      id: todayEntry?.id || crypto.randomUUID(),
      date: new Date().toISOString(),
      mood: selectedMood,
      note,
    };

    onAddEntry(newEntry);

    setTimeout(() => {
      setIsSubmitting(false);
    }, 500);
  };

  return (
    <Card className="w-full transition-all duration-300 hover:shadow-lg border-none overflow-hidden bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm">
      <CardContent className="p-6 md:p-8">
        <div className="flex items-center gap-2 mb-6">
          <HeartHandshake className="h-5 w-5 text-primary" />
          <h2 className="text-xl font-semibold">
            How are you feeling today?
            {mounted && (
              <span className="ml-2 text-xs text-muted-foreground">
                {resolvedTheme === "dark" ? "🌙 Dark mode" : "☀️ Light mode"}
              </span>
            )}
          </h2>
        </div>

        <div className="flex justify-center gap-6 mb-8">
          {moods.map((mood) => (
            <button
              type="button"
              key={mood}
              onClick={() => setSelectedMood(mood)}
              className={`text-4xl p-4 rounded-full transition-all duration-300 transform hover:scale-110 shadow-sm
                ${
                  selectedMood === mood
                    ? `${moodColors[mood]} text-white scale-110 shadow-md`
                    : "bg-secondary hover:bg-secondary/80"
                }`}
              aria-label={`Select mood: ${mood}`}
            >
              {mood}
            </button>
          ))}
        </div>

        <div className="mb-6">
          <Textarea
            placeholder="Add a note about your day (optional)"
            value={note}
            onChange={(e) => setNote(e.target.value)}
            className="resize-none min-h-[120px] bg-white/50 dark:bg-gray-800/50 backdrop-blur-sm border-primary/10 focus-visible:ring-primary/20"
          />
        </div>

        <Button
          onClick={handleSubmit}
          disabled={!selectedMood || isSubmitting}
          className="w-full bg-gradient-to-r from-primary to-purple-500 hover:from-primary/90 hover:to-purple-500/90 transition-all duration-300"
        >
          {todayEntry ? "Update" : "Save"} Today&apos;s Mood
        </Button>
      </CardContent>
    </Card>
  );
}
